version: '3'
services:
  postgres:
    image: postgres:13
    restart: always
    env_file:
      - "./database.env"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  python_app:
    restart: always
    depends_on:
      - postgres
    build: .
    environment:
        - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
    env_file:
      - "./database.env"
    ports:
      - "5555:5000"
    volumes:
      - ./services/web/:/usr/src/app/

volumes:
  postgres_data: